enocean/__init__.py

Add complete list of common command codes for further development
Add headers for the changed sections
----
Changes:
Line 68 - 154: Add headers to definitions
Line 95 - 132: extend List of Common Command Codes (to all available commands) 
Line 165: change Version number
Line 748 - 758: Add header for crc claculation

Enocean: extend command command codes

---

operationlog/README.md
operationlog/__init__.py

This patch will add support to configure logic using `operationlog` plugin to generate a log message each time the logic was triggered.
The feature is not new, it was previously implemented in the `memlog` plugin. Since the operationlog is a little bit more useable (can log to file, can cache the log, ...) I would also suggest to completely remove the `memlog` plugin later (not part of this PR).
To configure such a message for a logic trigger you can use the following settings in the `logic.conf`:
* olog = \<name\>
* olog_txt = "...."
* olog_level = \<level\>
PS: I added myself to the copyright notice since I think parts and ideas are from the original `memlog` plugin. Hope it's OK. If not, let me know.

Add logic trigger to operationlog

---

dmx/__init__.py

I'm using the DMX Adapter www.enttec.com/dmxusbpro. Some time ago I modified the DMX plugin to support this type of adapter and created a pull request to integrate the changes. In the meantime there were some incompatibilities with a new python version (v3.x) and I modified the plugin accordingly + used a more readable code

modified enttec plugin for python3

---

sma/__init__.py

This will check if the socket type AF_BLUETOOTH is available in the
socket module to avoid exceptions or error user will not be able
to handle. If Bluetooth support is not available hint the user to
install it and look up instructions in the readme.
See also https://github.com/smarthomeNG/smarthome/issues/229

Check if Bluetooth support is available in socket module

---

knx/__init__.py

This PR fixes a minor typing error in two methods from the KNX plugin. Replaced #73 which was requested to the wrong branch.

KNX typo fix

---

visu_smartvisu/tplNG/category.html
visu_smartvisu/tplNG/category_page.html

By default, category site contained `category_nav` in `sidebar block` and bunch of broken links in German in `content block`. Since there's no sidebar in smaller resolutions (like mobile phones), there's no other access to category item than manually editing address. This commit changes category behavior to act similar to rooms:
-  `category_nav` in `content block` when selected category from menu; clock & weather in `sidebar block`
-  `category_nav` in `sidebar block` when selected specific category from  `category_nav`

visu_smartvisu: fix category menu on mobile devices

---

avdevice/__init__.py

If power socket is off, a command gets stored temporarily to be sent after connection to av device is  established. This function was broken in some cases.

AV Device plugin: fixed bug depending keepcommands function

---

enocean/README.md
enocean/__init__.py
enocean/eep_parser.py

- add empty line between two methods
- only send logger.info for Eltako FAH60 when Brigthness > 0
- add header for RORG = D2
- small improvements of comments
- Add brightness sensor example for item.conf in Readme.md
- remove 6 x return None. Was forgotten to remove

Enochean Bugfix

---

avdevice/AVDeviceInit.py
avdevice/Denon_Items.yaml
avdevice/Pioneer_Items.yaml
avdevice/README.md
avdevice/__init__.py
avdevice/denon-avr6300.txt
avdevice/plugin.yaml
avdevice/sc-lx86.txt
avdevice/vsx-923.txt

changed some debug levels and text
changed standard ignore responses (relevant for Pioneer receivers)
added example item files as additional YAML
changed search path for config files to folder of plugin
updated config files
improved handling of string type commands
added option to define multiple responsetypes separated by pipe (, is still possible)

Avdevice plugin: updated config files, small fixes

---

enocean/plugin.yaml

- type of BaseID has to be a string
- type of enocean_rx_id has to be a string
- type of rx_key has to be a string

# Bugfix: plugin.yaml

---

.travis.sh
.travis.yml

This is an update for the Travis-CI build:
* updated `tox.ini` and `.travis.yml`
* introduced new `.travis.sh` script which is used to run the suite
It will enable execution of tests when committing to the `plugins` repository. An example run can be reviewed [here](https://travis-ci.org/ohinckel/smarthomeNG-plugins/jobs/328406633). The [documentation](https://github.com/smarthomeNG/smarthome/wiki/Tests) will also be updated after merge.
The execute will be unified with this PR so that the `plugins` and `core` repositories uses the same script and configuration and run the suite as follows:
* commits to `master` will run the tests using both repositories' `master` branch
* commits to `develop` will run the tests using both repositories' `develop` branch
(see also …

Update Travis-CI build

---

avdevice/denon-avr6300.txt

As Standby can be set to "off" or a value like "8H" it's necessary to set the type to string|bool

fixed type for standby command in text-file

---

avdevice/__init__.py
avdevice/plugin.yaml

If command like 'PO|PO' is sent the command isn't removed even when response is as expected. Fixed this bug.

AVDevice: fixed problem with multi-command

---

database/__init__.py

When the database connection can not be setup while SmartHomeNG is starting the database plugin setup will fail completely. This means not database support is enabled until SmartHomeNG is restarted (which will try to connect to the database again).
This patch will postpone the database plugin initialization to a later point. To be more exact it will try to establish the connection on startup and logging a warning in case of failure, but does not disable database support completely. Instead it will retry to establish the connection on each database access attempt.
Since the code is now checking if the connection is established and initialized on each database access, it will slow down the processing a little bit. But checking a boolean might not be a powerful operation...
This feature was …

Move database connection initialization to later point

---

slack/README.md
slack/__init__.py
slack/plugin.yaml

Made a mistake when switching rthill's fork from upstream:master to upstream:develop. @rthill: sorry for messing things up!
Thus I started a clean fork and re-added the slack dir and its three files.
Original discussion was at pull request #144 and shall be continued here.

Re-Add slack plugin

---

stateengine/StateEngineItem.py

Fix the issue described in https://github.com/i-am-offline/smarthome.plugin.autoblind/issues/24
Reason was, that in the item class "_eval_trigger" seems to be replaced by "_trigger".

[Bug] Fix "Rules not evaluating with new SmarthomeNG 1.5 master"

---

database/__init__.py

This introduces a new function called `countall` to get the amount of log entries.
E.g. when you want to retrieve the amount of log entries for a given item you can use
```
item.db('countall', 0)      # return amount of entries with start-time=0 until now (= all)
item.db('countall', '-1w')  # return amount of entries with start-time=-1 week until now
```
Querying the values as series is also possible by using:
```
item.series('countall', '0')    # return amount with start-time=0 until now (= all), grouped by 100 entries (default) 
item.series('countall', '-1w')  # return amount with start-time=-1 week  until now, grouped by 100 entries (default) 
```
I'm not sure if this is really a use-case, but with this it would be possible to show the data increase in a chart for a time range and an …

Database: Add new countall function to get amount of log entries returned

---

knx/Check_KNX.py

Creates the following output at the end of the report. (Example lines only)
A type comparison has to be done manually e.g. in Excel. But with this output gaps/delta between ETS Configuration and Items can be easily spotted.
```
Folgende Items sind mit Bezug zu KNX konfiguriert:
======================================================================
item                                                             |type      |dpt       |GA        |bindtype  |ETS Name
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
wurzel.zentral.klingelknopf                                 |      bool|         1|     0/3/5|knx_listen| in ETS => Globale Daten.Meldungen.Türklingel Klingeln …
```

Added all item to ETS-OPC (.esf-File) comparison

---

openweathermap/README.md
openweathermap/__init__.py

This allows the openweathermap plugin to use the free API for forecasts.
Forecasts are received as 40 distinct 3-hours timeslices.
To provide daily forecasts, the average/min/max of those 3-hours slices is calculated.
The forecast is matched by using "forecast/x/" where x is between 0-39 and indicates the index of the 3-hour prediction from the API.
Daily forecasts are matched by using "forecast/daily/x" where x is "days-in-future - 1", so it ranges from 0-4. (We don't have complete forecast data for the current day)
Up for discussion:
- Use daily index 0 for current day, even if it is possible we have NO prediction (e.g. if forecast was requested at 22.00 the first prediction is already for the next day)?
- Is it okay for you to assume that "the temperature" is the average of all …

openweathermap: Add support for forecast data

---

knx/README.md
knx/__init__.py
knx/plugin.yaml

added support for using hostname instead of ip address for "host" parameter of plugin config. Adjusted documentation accordingly

knx: added hostname support

---

trovis557x/__init__.py

There was no special handling for those few 16bit registers that can hold negative values (signed INT's).
Therefore, negative temperatures resulted in ridiculous values, like 6.552,7°C outside temperature instead of a real reading of -0.8°C.
Also, fixed some doublettes in comments.

Corrected processing of negative 16-bit register values

---

mailrcv/__init__.py
mailrcv/plugin.yaml

This PR contains of two small bugfixes:
**Trashfoder option:** 
Depending on the configuration of the IMAP server, the Trash folder can have different names.
To move a read mail to trash, the mailplugin has to know that name. Added the possibility to change
the name of the trashfolder.
If deleting the mail fails a list of abailable folders is written to the log.
**Emails without content-transfer-encoding header**
According to RF1341, emails can but must not contain the content-transfer-encoding header. (https://www.w3.org/Protocols/rfc1341/5_Content-Transfer-Encoding.html).
If this header does not exist, the python email package does not allow decoding of the message (at least in some versions).
To resolve this we simply set the content-transfer-encoding header to 7BIT, which is the …

Mailrcv plugin: Added option to change name of trash and fixed a problem occuring when decoding emails

---

rcswitch/README.md
rcswitch/__init__.py
rcswitch/plugin.yaml

Add hostname support for switching via remote machine.
Now Hostname or IPv4 adress is possible for optional parameter `rcswitch_host`
Example:
`rcswitch_host: 192.178.165.23`
`rcswitch_host: pi-smarthome1`

[RCswitch]: Add Hostname support

---

thz/PortHandler.py

The THZ plugin had a problem with the serial connection to my heatpump:
```
ERROR    plugins.thz.THZ Heat pump did not respond for 10 seconds
WARNING  plugins.thz.THZ (<class 'AttributeError'>, AttributeError("'PortHandler' object has no attribute 'closePort'",), <traceback object at 0x7fd34c03aa88>)
```
I figured the `closePort ` method should close the port, so i added the missing method in PortHandler.py.
I don't know if we need exception handling there and also I couldn't test it yet, but I'm quite sure the method should be there as it is called here: https://github.com/smarthomeNG/plugins/blob/80e41af31ed53e405d5e89ed7091ffc4696c71d9/thz/ThzProtocol.py#L1254

thz: Add missing method

---

telegram/__init__.py
telegram/plugin.yaml

Currently, using the Telegram plugin with this configuration:
telegram:
class_name: Telegram
class_path: plugins.telegram
name: <something>
token: <top secret>
welcome_msg: ""
bye_msg: ""
yields the error message 
2020-01-04  17:15:51 ERROR    plugins.telegram    could not broadcast to chat id [...] due to error Message text is empty
This PR corrects this and allows empty (and hence disabled) welcome and bye messages without error.

Telegram: Removed error message when welcome_msg or bye_msg is empty

---

alexa4p3/p3_action.py

Updated p3_action.py for smarthomeNG item updates, so that the updater is identified within SH as "Alexa". With this it is possible to differentiate item changes in other plugins/logics like simulation for example...

Alexa4p3: Added plugin identifier

---

ical/README.md
ical/__init__.py
ical/plugin.yaml

iCal calendar uris can have embedded login data, e.g. https://user:password@domain.tld/path
It might not be advisable to output this login data to logfiles.
The new plugin configuration parameter handle_login can be
'show': output login data (current behaviour) -> https://user:password@domain.tld/path
'mask': replace login data with '***' respectively -> https://***:***@domain.tld/path
'strip': strip login data completely -> https://domain.tld/path
default is 'mask', which changes default behaviour, but is a safe preset
Check and handling is located in iCal._clean_uri() which is in turn called before logging calendar data. Attention must be paid if future additional logging is done.

Plugin iCal: added handling of logging login data in calendar uris

---

yamahayxc/plugin.yaml

'description_lone' -> 'description_long'

Plugin yamahayxc: fixed typo

---

onewire/__init__.py

Fixes ValueError: cannot switch from automatic field numbering to manual field specification

Onewire Plugin fix format string in debug output

---

avm/__init__.py
avm/plugin.yaml

Hey,
I've added some arguments for the hkr_device ('firmware_version',  'manufacturer',  'product_name', 'device_name', 'connection_status', 'device_id', 'device_function'). Also I changed the logger output to make the message of error more specific.
Furthermore I changed the plugin revision to 1.5.9 
Michael

AVM_Plugin: new arguments for hkr_device added

---

xmpp/README.md
xmpp/__init__.py
xmpp/plugin.yaml
xmpp/requirements.txt

The XMPP Python library [sleekxmpp](https://github.com/fritzy/SleekXMPP) is no longer maintained the the repository is archived. There's a replacement library called [slixmpp](https://github.com/poezio/slixmpp).
Changing the XMPP plugin to use the new library (with some adjustments to the methods used). But mostly it seems to be compatible.

XMPP: Replace sleekxmpp with slixmpp

---

avm/__init__.py

AVM-Plugin: If there is no 'call_duration_incoming' item, then a KeyError happens when trying to access self._duration_item['call_duration_incoming']. This exception is caught, but then when trying to log this error an exception occurs. This second exception is reported to console only. That means nothing is written to the log.
This pull request fixes the logging error and also creates the dictionary entries 'call_duration_outgoing' and 'call_duration_incoming'.

Avm plugin fixes

---

stateengine/StateEngineAction.py

convert source for actions/item changes to string, otherwise this can create errors e.g. when using log_change attribute

Stateengine Plugin: important fix for action source

---

alexarc4shng/__init__.py

In __init__.py around line 271 we find:
```
try:
myEchos = self.sh.alexarc4shng.Echos.all()
except Exception as err:
self.logger.debug("Error while getting Echos :",err)
```
Isn't that working only when the plugin is named "alexarc4shng"?
In the plugins README.md it is written:
`plugin_name -> fix AlexaRc4shNG`
So it must be accessed by
`self.sh.AlexaRc4shNG.Echos.all()`
or?
And right, when I debug through it it still throws an exception:
`AttributeError("'SmartHome' object has no attribute 'alexarc4shng'")`
Because myEcho isn't used afterwards anyway it can be removed ...

plugin alexarc4shng: Unused code

---

rcswitch/__init__.py
rcswitch/plugin.yaml

- changed valid list for rc_device to:
valid_list: ['1','2','3','4','5','a','b','c','d','e','A','B','C','D','E']

[plugins/rcswitch]: BUGFIX in plugin.yaml for shng v1.8.1

---

stateengine/StateEngineItem.py

If the items lastconditionset/lastconditionset_name are not set and one tries to generate the graph in the web interface an exception occurs.
The pull request avoids the exception. The graph is generated.

Avoid exceptions when lastconditionset/lastconditionset_name item is not set

---

knx/__init__.py
knx/dpts.py
knx/plugin.yaml

Implemented & Tested for MDT DaliControl Gateway
6 Bytes Object, but only the 4 Bytes are actually used according to docu.
The first 2 Bytes are filled with '0xff' as default values

knx plugin: add DPT 251.600 RGBW

---

avm/__init__.py

Nearly every night my SmarthomeNG has a connection problem with the fritz box. In this moment an exception occures in the listen thread and the thread terminates. Of couse the call monitor is not working anymore after that.
This commit fixes that behavior as it sets the _listen_active flag to false before terminating the thread. The inherent reconnect behavior then detects this situation and start a new listen thread.
On shutting down SmarthomeNG it stops the listen thread by a rude shutdown of the socket. There is no other way to get in contact with this thread. Alternatively one could set a socket timeout and check for the stop flag ...
Also it now stores a handle to the running listen thread (`start()`still returns None) and uses this for joining.

avm: Handle callmonitor reconnect

---

mailrcv/__init__.py

e.g. prevent error message like this:
WARNING  plugins.mailrcv   IMAP: Could not select mailbox
ERROR    plugins.mailrcv.IMAP Method plugins.mailrcv.IMAP exception: command CLOSE illegal in state AUTH, only allowed in states SELECTED
Traceback (most recent call last):
File "/usr/local/smarthome/lib/scheduler.py", line 664, in _task
obj()
File "/usr/local/smarthome/plugins/mailrcv/__init__.py", line 76, in _cycle
imap.close()
File "/usr/local/lib/python3.8/imaplib.py", line 466, in close
typ, dat = self._simple_command('CLOSE')
File "/usr/local/lib/python3.8/imaplib.py", line 1205, in _simple_command
return self._command_complete(name, self._command(name, *args))
File "/usr/local/lib/python3.8/imaplib.py", line 943, in _command
raise self.error("command %s illegal in state %s, " …

mailrcv plugin: catch exception when trying to close imap

---

shelly/__init__.py
shelly/plugin.yaml
shelly/user_doc.rst

docs for shelly flood mqtt: https://shelly-api-docs.shelly.cloud/#shelly-flood-mqtt
the missing entry for shelly1 can also be read in the docs and is verified by me:
https://shelly-api-docs.shelly.cloud/#shelly1-1pm-mqtt
thats a view on my broker for the new flood device

Some updates for the shelly plugin

---

smlx/__init__.py

Hello together,
i was migrating from smarthomeng v1.5.1 to v1.9.1 and now using the smlx plugin. Before I have used the sml plugin.
I noticed WARNINGs about an incompatible string (manufactor + serial number) coming from the smlx plugin to the item.
`
2022-03-13 20:10:45 CET WARNING  item              plugins.smlx.Smlx Item Energie.Strom.Zaehler.Hersteller: value "b'EMH'" does not match type str. Via Sml None  --  (item.py:__update:1536)  
`
This pull request will fix this by expanding the obis codes for EMH ED300L smartmeter to convert the byte values to a nicer format.
This is tested on my installation and it works quite fine.
Happy to see this in a future release.
Kind Regards,
Julian

smlx: convert EMH ED300L values to nicer format

---

modbus_tcp/__init__.py

Fixes race condition problems with high poll rates and speeds up plugging massively by keeping the TCP connection open.
Tcp connection is automatically re-established in case of error.

modbus_tcp: keep connection open and use locking to ensure thread safety

---

stateengine/sv_widgets/stateengine.html

As of smartVISU v3.3 widgets get imported using a namespace `@widgets` containig the widgets paths. 
With this PR, the widget import method is depending on the smartVISU version which makes the widget backward compatible..

stateengine plugin: add SV widget namespace import

---

viessmann/__init__.py
viessmann/plugin.yaml

In method "_bytes2int" wrong bytorder has been used

Viessmann Plugin: Bugfix in method "_bytes2int"

---

hue2/__init__.py

Allows direct routing of multipe options to the qhue library. This makes it possible to simultaneously change e.g. brightness and color or turn on a lamp with a certain color or brightness.
The advantage of the simultaneous change is a very nice even fading between the states.
Since the dictionary is passed directly to the qhue library, which generates the API requests dynamically from the function call, all functions from the hue-api are supported.
Also e.g..  "effect", "colormode", "alert", "transitiontime".
See hue api:
http://www.burgestrand.se/hue-api/api/lights/
https://developers.meethue.com/develop/hue-api-v2/
Example:
```
{
"on": True,
"transitiontime": 10,
"bri": 255,
"ct": 370
}
```

hue2: fix multiple functions at once

---

knx/webif/templates/index.html

If knx_listen just contains 1 entry, it will be shown directly. 
If knx_listen contains more than 1 entry, it will be shown as list.

Adapt handling of knx_Listen

---

sonos/__init__.py
sonos/plugin.yaml
sonos/sv_widgets/widget_sonos.html
sonos/user_doc.rst

- general: - remove try/except for import of external modules; already part of smartplugin-class
- __init__.py
- class Speaker
- add method _play_favorite
- add method play_favorite_title
- add method play_favorite_number
- add method _play_favorite_radio
- add method play_favorite_radio_number
- add method play_favorite_radio_title
- remove check if tinytag is available; already done at startup
- implement _play_radio as general method to play radio from music services (based on play_tunein, reworked to use Soco instead of direct post request)
- reworked play_tunein to call _play_radio
- add play_sonos_radio to call _play_radio
- adapt _av_transport_event to show radio station if started via plugin
- class Sonos(SmartPlugin)
- bump version to 1.8.0
- __init__
- delete check of …

Bugfixes / Enhancement to Sonos Plugin

---

stateengine/StateEngineItem.py
stateengine/user_doc/10_funktionen_variablen.rst

so they can be used in enter Conditions. Not sure why this was different before..?

stateengine plugin: keep variables after state evaluation 

---

avm/__init__.py
avm/plugin.yaml
avm/user_doc.rst

- Bump to 2.0.5
- NEW get_hosts_dict: enable "only_active"
- NEW get_hosts_list: returns list for (filtered host); provides more flexibility and much quicker results as get_hosts
- BUGFIX is_host_active
- BUGFIX get_hosts
- UPDATE get_hosts_dict
- NEW get_hosts_count: Enable only_active
- UPDATE plugin.yaml
- UPDATE user_doc.rst

AVM Plugin: Bugfix and Extension of 'get_hosts'

---

.github/workflows/unittests.yml

The unittests in new branches (for example this workflow) of forks from smarthomeNG/plugins fail always on `Checkout core from branch 'workflow' (for push)` because they are trying to checkout the actual (workflow) branch from the smarthomeNG/smarthome repo.
This branch obviously does not exist on most of the plugin development cases. But sometimes it could also be useful, for example if someone is working, lets say, on plugins/smartvisu and there is a associated development on the smarthome websocket module with the same branch name.
So instead of removing this workflow step, I added a check if such a branch exists in smarthomeNG/smarthome, if its there it gets checked out, if not the develop branch gets checked out.
And in the following steps instead of checking out the …

Workflow: Fix unittest for forked repos

---

executor/__init__.py
executor/examples/check_device_presence.py
executor/examples/check_items.py
executor/examples/database_count.py
executor/examples/database_series.py
executor/plugin.yaml
executor/user_doc.rst
executor/webif/__init__.py
executor/webif/templates/index.html

Major fix for autocomplete
Performance improvements (loading autocomplete takes 15s for me and blocked the webif..)
Sorting option for saved files

Executor Plugin: Improvements and fixes

---

avm/__init__.py
avm/plugin.yaml

- FritzHome: Bugfix renewing SID in case SID has expired
- CallMonitor: bugfix join listing thread
- CallMonitor: reconnect if connection is lost
- bump to 2.0.9

AVM: Bugfix

---

enocean/__init__.py
enocean/plugin.yaml
enocean/user_doc.rst

This change is in reference to [this thread](https://knx-user-forum.de/forum/supportforen/smarthome-py/1872963-verlust-von-serial-device-bringt-enocean-und-smarthomeng-zum-absturz) at the KNX user forum. 
The `serial.Serial()` constructor from pyserial was replaced with `serial.serial_for_url()`, which supports both the traditional unix file handle (e.g. `/dev/ttyAMA0`) and RFC2217-compliant URLS (e.g.`rfc2217://<IP>:<PORT>`) interchangeably. 
Error handling was added to deal with connection breakdowns and reinitiate the connection. In case of a connection breakdown at transmission time, one attempt at retransmission will be made. Afterwards, the packet will be lost.
It's not clear to me if the run method will be restarted on successful reconnection after the loop has been broken (change …

Support RFC2217 connections for enocean plugin

---

stateengine/StateEngineAction.py
stateengine/StateEngineFunctions.py
stateengine/StateEngineItem.py
stateengine/StateEngineLogger.py
stateengine/StateEngineTools.py
stateengine/webif/templates/visu.html

Stateengine Updates for recent scheduler/caller changes in core

---

byd_bat/__init__.py
byd_bat/plugin.yaml
byd_bat/requirements.txt

Modifications for mathplotlib 3.8.0, minor changes

Plugin byd_bat: Modifications for mathplotlib 3.8.0

---

pushover/README.md
pushover/__init__.py
pushover/plugin.yaml

neuen Parameter TimeToLive (https://pushover.net/api#ttl) eingebaut

pushover: add ttl parameter

---

xiaomi_vac/requirements.txt

because otherwise creating wheel of newer version might not work for Raspi bookworm

xiaomi_vac plugin: add zeroconf 0.52.0 as requirement 

---

homematic/__init__.py

2024-02-24  23:02:35 ERROR    cherrypy.error.140734358467536 [24/Feb/2024:23:02:35] HTTP 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/cherrypy/_cprequest.py", line 638, in respond
>     self._do_respond(path_info)
>   File "/usr/local/lib/python3.10/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
>     response.body = self.handler()
>   File "/usr/local/lib/python3.10/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
>     self.body = self.oldhandler(*args, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
>     return self.callable(*self.args, **self.kwargs)
>   File "/usr/local/smarthome/plugins/homematic/__init__.py", line 556, in index
> …

homematic: fixing WebInterface for items with the same name

---

solarforecast/__init__.py
solarforecast/plugin.yaml

power checks are provided as item struct and as a plugin function, see plugin.yaml

solarforecast: add hourly forecast and power checks

---

modbus_tcp/__init__.py
modbus_tcp/plugin.yaml
modbus_tcp/user_doc.rst

Error when writing registers fixed
Improved conversion of byte/word order to endian constant

[modbus_tcp plugin]: fixed error writing registers, conversion byte/word to endian

---

database/__init__.py
database/plugin.yaml
database/webif/__init__.py
database/webif/static/style.css
database/webif/templates/base_database.html
database/webif/templates/index.html

Wie im gitter schon geschrieben, komme ich hier nicht weiter. Die Parameter orphanID und newID (im WebUI/JS) sollten an das WebIf (orphan-id, new-id / Python) übergeben werden. Das geht aber (hier?) nicht mehr, und ich habe keinen Plan, wieso.
Falls jemand dazu einen Vorschlag hat, wäre das super...

database: change reassignment selection to modal dialogue

---

database/__init__.py
database/plugin.yaml

The time precision is currently 1ms. With the new parameter time_precision, that can be changed to, e.g. seconds (time_precision = 0). That avoid problems in visualization. The storage of data in the database is not affected

database: adding customizable time_precision

---

sonos/__init__.py
sonos/plugin.yaml

- bump to 1.8.9
- improve _handle_dpt3
- make plugin restartable

Sonos Plugin: improve dpt3 handling, make plugin restartable
