smarthomeNG/plugins

- enocean/__init__.py
- enocean/eep_parser.py
added changes after review from ohinickl
> Enocean Plugin

- influxdb/README.md
- influxdb/__init__.py
started as a fork of influxdata which is lacking too much and I had to give it a proper name (influxdata is the vendor/company that also procudes the product/database infuxdb)
> InfluxDB Plugin

- nuki/__init__.py
There was a forgotten check for a 'None'-value. Fixed now.
> small bugfix for Nuki plugin

- sonos/README.md
- sonos/requirements.txt
python package xmltodict added
> package xmltodict added

- squeezebox/__init__.py
playlist name gets polled when new tracks are loaded in playlist.
> Squeezebox plugin: added automatic request of playlist name

- wol/README.md
- wol/__init__.py
Added an option to specify an IP Adress to wake up. Needed when waking up hosts in another subnet (no in the same broadcast domain).
> Wol ip address

- enocean/README.md
Changes:
-     redesign Headers for give a structure (lines: 4, 37, 65, 174, 200, 210, 240)
-     rework of chapter --- **Configure plugin.conf** --- (lines 3 - 35)
-     rework of chapter --- **Configure items** --- (lines 37 -63)
-     rework of chapter --- **Example item.conf** --- (lines 65 - 69)
-     rework of chapter --- **Add new listening enocean devices** --- (lines 174 - 198)
-     rework of chapter --- **Send commands: Tx EEPs** --- (lines 200 - 208)
-     rework of chapter --- **Learning mode** --- (lines 210 - 237)
-     rework of chapter --- **UTE teach-in** --- (lines 239 - 246)
-     change of version to v 1.4
> Encocean: Update README.md

- alexa/README.md
- alexa/__init__.py
- alexa/action.py
- alexa/actions_turn.py
- alexa/device.py
- alexa/service.py
see updated readme regarding the new `alexa_alias` item-configuration
> Supporting Alias-Names & Scenes

- alexa/README.md
- alexa/__init__.py
- alexa/action.py
- alexa/actions_turn.py
- alexa/device.py
- alexa/service.py
Reverts smarthomeNG/plugins#47
> Revert "Supporting Alias-Names & Scenes"

- alexa/README.md
matching https://github.com/smarthomeNG/smarthome/issues/209
> corrected headline formatting

- gpio/README.md
- gpio/__init__.py
Change to GPIO.event_detect to streamline plugin
> Updated plugin GPIO

- nut/README.md
- nut/__init__.py
Hi,
Recently I created this new plugin to connect with NUT - Network UPS Tools daemon. So far works fine with my server, now it's time to share :) I tried to make it SmartPlugin and multiinstance (to work with more than one ups device).
Can anyone test it? :)
4d4mu
> NUT - new plugin

- avdevice/__init__.py
- avdevice/denon-avr6300.txt
Please test esp. other devices than Pioneer and Epson and post issues here:
https://knx-user-forum.de/forum/supportforen/smarthome-py/1097870-neues-plugin-av-device-für-yamaha-pioneer-denon-etc
> Lots of bug fixes, Denon support for boolean commands (more coming soon)

- pushover/README.md
- pushover/__init__.py
- pushover/requirements.txt
Hi, this is my initial version of Pushover Plugin.
> Initial version of Pushover Plugin

- artnet/README.md
- artnet/__init__.py
- comfoair/README.md
- comfoair/__init__.py
- datalog/README.md
- datalog/__init__.py
- luxtronic2/README.md
- luxtronic2/__init__.py
- memlog/README.md
- memlog/__init__.py
Made some plugins a smartplugin and adjusted READMEs.
> Make plugins a SmartPlugin: datalog, memlog, comfoair, artnet, luxtronic2

- dlms/__init__.py
to support smartmeters with bogus checksums like itron ace3000.
most changes caused by atom.io cleaning up spaces and stuff. actual change is only line 409
> make use_checksum actually work again

- avdevice/AVDeviceInit.py
- avdevice/README.md
- avdevice/__init__.py
- avdevice/denon-avr6300.txt
- avdevice/plugin.yaml
PEP8 optimized code
updated plugin.yaml and README
updated reset function for Denon receivers when no correct response received
updated automatic optimization of send command list
added debug verbose levels 8 and 9
full zone 2 and 3 control possible
added a lot of new commands to Denon text file
fixed some bugs especially regarding the response parsing process
> Avdevice plugin: v. 1.3.1

- sonos/README.md
- sonos/__init__.py
- sonos/examples/sonos.yaml
- sonos/requirements.txt
- sonos/tts.py
- sonos/utils.py
Adding Goolge TTS and snippet audio file functionality.
> Google TTS and Snippet audio functionality added

- sonos/README.md
- sonos/__init__.py
- sonos/plugin.yaml
- sonos/utils.py
support for static ip addresses
updated documentation
plugin version tagged to v1.4
> Added support for static ip addresses

- mpd/README.md
- mpd/__init__.py
- mpd/plugin.yaml
added support for loading and playing local playlists which means sending the following commands to MPD to play a playlist:
clear
load filename
play
> MPD: added support for loading and playing local playlists

- enocean/__init__.py
Changes:
- move all learn methods in one "Learn methods section" at the end of the file
- correction of payload for send learn switch
- change logger.warning --> logger.info
- change logger-debug --> logger.info
- restructure existing learn methods like that:
1. define RORG
2. define PAYLOAD
3. send(RORG, PAYLOAD)
4. logger(RORG, PAYLOAD)
The benefit is the payload can be used directly in the send command an the logger.
logger-format: rorg = a5 / payload = [0xe0, 0x40, 0x0d, 0x80]
benefit of this changes is to define only one learn methods for future improvements and calculate in a switch...case construction thr rorg and payload.
> Enocean: restructure of learn methods

- database/README.md
- database/__init__.py
- database/tests/test_series.py
- database/tests/test_single.py
This is the implementation for issue https://github.com/smarthomeNG/smarthome/issues/235 which includes new aggregation functions and introduce finalizer function.
> Database plugin: more aggregation function sum, count, val

- xbmc/__init__.py
added shutdown command. one can now use xbmc_send = shutdown in items.conf
> XBMC: added shutdown command

- enocean/README.md
- enocean/__init__.py
1. enhance learn method:
- change learn methods into one learn method for the enocean devices.
- construction with if...elif
2. Docu changes in readme and improve readibility
- docu changes in readme
- changes tab setting for device description
> Enochean Enhance Learn Method-2

- enocean/README.md
- enocean/eep_parser.py
- optimize logger format
- introduce headings for differrent RORGs
- optimize comments
- add parser for Eltako brigthness sensor FAH60
- correction of logger (logger --> self.logger)
> Enocean update eep parser

- lirc/README.md
- lirc/__init__.py
- lirc/plugin.yaml
with this changes the plugin is working again with the current release of SHNG
> LIRC: adjustments for SHNG 1.4

- rcswitch/__init__.py
- rcswitch/plugin.yaml
- update of actual version 1.2.0.3
- forgot to update tthe plugin.yaml by the last __init__ update.
Sorry.
>  # rc-switch: Update of Plugin.yaml

- enocean/README.md
- enocean/plugin.yaml
- update parameters
- update of attributes
- rework the readme.md
- replace aschwith and Rbudde as maintainer and tester
> Enocean: update of plugin.yaml and readme.md

- sonos/README.md
- sonos/__init__.py
- sonos/examples/sonos.yaml
- sonos/plugin.yaml
- sonos/soco/__init__.py
- sonos/soco/cache.py
- sonos/soco/compat.py
- sonos/soco/core.py
- sonos/soco/data_structures.py
- sonos/soco/data_structures_entry.py
- sonos/soco/discovery.py
- sonos/soco/events.py
- sonos/soco/groups.py
- sonos/soco/ms_data_structures.py
- sonos/soco/music_library.py
- sonos/soco/music_services/accounts.py
- sonos/soco/music_services/data_structures.py
- sonos/soco/music_services/music_service.py
- sonos/soco/plugins/example.py
- sonos/soco/plugins/wimp.py
- sonos/soco/services.py
- sonos/soco/snapshot.py
- sonos/soco/soap.py
- sonos/soco/utils.py
- sonos/soco/xml.py
- added parameter to set a dedicated audio snippet path
- newest SoCo framework update
- Bugfix: an error was thrown if no default tts language was set
- updated documentation
> Sonos plugin feature update / bugfixes

- harmony/__init__.py
- harmony/plugin.yaml
Bugfix: 'unknown activity' in debug log
updated documentation
> Harmony plugin bugfixes

- telegram/README.md
- telegram/__init__.py
**new optional function-parameter to send message to individual chat_id's:**
def _msg_broadcast(self, msg, chat_id=None):
**new function to send pictures**
def _photo_broadcast(self, photofile, msg, chat_id=None):
**new SH-Item-attribute to read specific SH-items via bot with the /info - command**
the plugin create a bot-keyboard.
e.g. telegram_info = wetter # SH-Item-attribute
**new command /lo:**
list all SH-logics
**new command /tr:**
trigger SH-logic e.g. /tr garagentor_auf
> telegram: individual chat_id's, picture, attribute: 'telegram_info', list logoc, trigger logic

- enocean/README.md
- enocean/__init__.py
- enocean/eep_parser.py
- enocean/plugin.yaml
- enocean/prepare_packet_data.py
- Improvements
- Bugfixing
- new file
- new features
- reorganize update_item function
--> improvement to add further actors easily without change of __init__ Method
- move actor funtions to new file prepare_packet_data.py
- add debug logging for each function for better debugging posibility
- introduce new file
--> new actuators has added in this file
--> file/funktion returns the necessary packed data
- rework of existing actuators with full function posibility (block_switch, block_dim_value, dim_speed, ... )
- update actual functions and functionality to the coresponding Eltako actuator description file
- rework actor response telegram F6_02_03 for shutter actor
- introduce new F6_02_03_01 for eltako shutter actor FSB61NP-230V, FSB71
- update examples with new features
> enocean: rework and improvement of update Item

- jvcproj/LICENCE
- jvcproj/README.md
- jvcproj/__init__.py
- jvcproj/plugin.yaml
Hey guys,
i want to add my [JVC D-ILA Control Plugin](https://knx-user-forum.de/forum/supportforen/smarthome-py/1188479-plugin-steuerung-von-jvc-d-ila-projektoren) to smarthomeNG plugins!
Is there a way to get write access, too?
Greetings, KNXinsHaus
> JVC D-ILA Control Plugin

- backend/webif/templates/plugins.html
make path for plugin web interfaces relative, this fixes issues when using docker or a reverse proxy
> make path for plugin web interfaces relative

- avdevice/AVDeviceInit.py
- avdevice/__init__.py
- avdevice/denon-avr6300.txt
- avdevice/sc-lx86.txt
- avdevice/vsx-923.txt
> Avdevice plugin: improved display ignore, response handling and logging

- avdevice/AVDeviceInit.py
- avdevice/__init__.py
- avdevice/plugin.yaml
- added dependency support
- added wildcard support (work in progress, not finished)
- tweaked code
> Avdevice plugin: major update

- avdevice/__init__.py
Sendcommands got removed from queue without being sent :(
> Avdevice plugin: fixed big bug

- avdevice/__init__.py
sorry bitte nicht ungetestet in den master - habs zu spät gesehen!!!!
Reverts smarthomeNG/plugins#148
> Revert "Avdevice plugin: fixed big bug"

- drexelundweiss/__init__.py
- drexelundweiss/plugin.yaml
- logging name
- init of serial package
- metadata support from plugin.yaml
- readonly items are now queried after update
> drexelundweiss: Updated logging and other stuff based on sample plugin

- iaqstick/__init__.py
- usb.core.find: returns list/no-list -> handle single/multi sensor
- usb.util.get_string: number of kwarg
- dev.read: number of kwarg
- dev.write: number of kwarg
> plugin iaqstick: changes due to latest pyusb updates

- enocean/README.md
- enocean/eep_parser.py
- enocean/prepare_packet_data.py
- Changes from #168 based on develop branch
> Support D2_01_12

- onewire/__init__.py
Previously, the Plugin disconnected from OWServer when a problem occured.
Now it tries to complete the sensor-cycle.
> Improved robustness to instable Busses

- rtr/README.md
- rtr/__init__.py
- rtr/plugin.yaml
- rtr/sv_widgets/widget_rtr.html
- rtr/sv_widgets/widget_rtr.js
some improvements and new features for rtr plugin.
> RTR develop

- zwave/__init__.py
- zwave/plugin.yaml
Hallo, ich bin endlich mal dazu gekommen den fix einzureichen...
> Zwave Plugin: fix endless loop

- mpd/README.md
> mpd plugin: Update README.md

- drexelundweiss/README.md
- drexelundweiss/__init__.py
- drexelundweiss/aerosilent_exos.txt
- drexelundweiss/plugin.yaml
> Drexel und Weiss Plugin: Aerosilent exos

- darksky/README.md
I think it is better to use relative items here. This way, it is likely, that a user can just copy and paste this code, even if he uses a different item structure as root of the weather.
> [darksky-plugin] update of readme with relative items

- enocean/webif/templates/index.html
- input type number
- defaultvalue = 0
- bound between 0 and 127
> # change input type

- knx/dpts.py
DPT 18.001 implemented and tested.
Documentation to follow
> DPT 18.001 implemented and tested

- rtr/__init__.py
… object at 0x7fd34ba354e0>>: 'str' object is not callable
> problem running <bound method RTR.stop_controller of <plugins.rtr.RTR object at 0x7fd34ba354e0>>: 'str' object is not callable

- rpi1wire/README.md
- rpi1wire/__init__.py
Nach mehrfachem Wunsch stelle ich dieses Plugin zur Verfügung. 
Dies ist mein erster pull request und ich weiß nicht ob es der richtige Weg ist ....
LG
> Plugin zum Auslesen von 1-Wire-Sensoren direkt am RPi angeschlossen

- helios/__init__.py
- helios/files/helios.yaml
- helios/plugin.yaml
- Remove startup error (cycle conversion from num to int fails)
- Make the data reading/writing 10 times faster (by error 70 instead of 7ms were used in the past)
- Changed logging of unknown received data (e.g. from noise on bus) to 'info' level
- Adjusted items.yaml to latest stand, some values are still under development
> Helios plugin error fix for 1.6 and some additional changes

- helios/__init__.py
- helios/files/helios.yaml
- helios/plugin.yaml
Reverts smarthomeNG/plugins#235
Was put against master instead of develop
> Revert "Helios plugin error fix for 1.6 and some additional changes"

- knx/README.md
> knx plugin: Update README.md

- stateengine/StateEngineAction.py
- stateengine/StateEngineCondition.py
- stateengine/StateEngineEval.py
- stateengine/StateEngineItem.py
- stateengine/StateEngineValue.py
- stateengine/user_doc/user_doc10.rst
age evaluation is now also possible when referencing to the item with "se_eval"
relative item references in evals are now possible as usual by using eval:sh...item()
current.action_name variable returns the name of the currently run action
> Stateengine plugin: new features and fixes

- stateengine/README.md
- stateengine/StateEngineAction.py
- stateengine/StateEngineCondition.py
- stateengine/StateEngineConditionSets.py
- stateengine/StateEngineDefaults.py
- stateengine/StateEngineItem.py
- stateengine/StateEngineState.py
- stateengine/StateEngineValue.py
- stateengine/__init__.py
- stateengine/plugin.yaml
- stateengine/user_doc/user_doc3.rst
- stateengine/user_doc/user_doc6.rst
improvements
additional feature/parameter: run leave actions directly after leaving state
> Stateengine plugin: v1.6.1

- trovis557x/readme.md
> Fixed broken link to Wiki in readme.md

- onewire/__init__.py
Compare does not work before conversion to float
> OneWire Plugin: Fixed error handling in case of readout problem (85 °C)

- darksky/README.md
- darksky/__init__.py
- darksky/plugin.yaml
- darksky/user_doc.rst
move info from data dict to daily and hourly, expand struct and docu
Current data dict is removed from the json response!
> darksky Plugin: v1.6.0 with fully expanded info and struct template

- stateengine/StateEngineAction.py
- stateengine/StateEngineActions.py
- stateengine/StateEngineEval.py
- stateengine/StateEngineItem.py
- stateengine/StateEngineState.py
- stateengine/StateEngineValue.py
- stateengine/StateEngineWebif.py
- stateengine/user_doc/user_doc1.rst
On init the currently evaluated values of eval are now logged on start up
All actions based on variables/dynamic items are now correctly initialised for the graph
Action values from the active state are updated after running through action in the web interface graph
> Stateengine Plugin: Improve Stateeninge Graph in Web Interface

- yamahayxc/LICENSE
- yamahayxc/README.md
- yamahayxc/__init__.py
- yamahayxc/plugin.yaml
- yamahayxc/requirements.txt
The yamahayxc plugin enables shNG.py to access and control Yamaha MusicCast AV devices. Current status is tested and working with those devices I have at home. 
Support thread is here: https://knx-user-forum.de/forum/supportforen/smarthome-py/1174064-plugin-yamaha-musiccast-ger%C3%A4te-neuere-generation
> new plugin yamahayxc for MusicCast devices

- helios_tcp/__init__.py
- helios_tcp/plugin.yaml
... Sorry, the last time I accidentally tested on the wrong branch and thus did not notice a few small mistakes.
> Helios_tcp: Fixed bugs introduced by last refactoring step

- avdevice/plugin.yaml
> AVdevice plugin: fix plugin.yaml

- stateengine/StateEngineAction.py
- stateengine/StateEngineActions.py
- stateengine/StateEngineItem.py
- stateengine/StateEngineState.py
now every situation should be handled correctly.
> Stateengine Plugin: improve collision handling when running multiple evals at the same time

- stateengine/StateEngineValue.py
fix current.\*_id/\*_name variables when used in conditions
previously some variables were ignored
PR can stay open until shortly before release. Maybe other stuff gets added ;)
> Stateengine Plugin: variable handling fixed

- alexa4p3/p3_action.py
Reverts smarthomeNG/plugins#305
> Revert "Alexa4p3: Added plugin identifier"

- squeezebox/__init__.py
> Squeezebox Plugin: update play,pause,stop items every time there is a change

- yamahayxc/README.md
- yamahayxc/__init__.py
- yamahayxc/plugin.yaml
added functionality for alarm clock settings (on supported devices)
minor fixes
included item struct functions require sh.py 1.7 (nested structs)
> Plugin: Yamahayxc - update to 1.0.6

- rcswitch/__init__.py
- rcswitch/plugin.yaml
- initialize user, ip, hostname with 'None'
- remove default value for user, ip, hostname
> [rcswitch] update of rcswitch to prevent Errors in SNHG v1.7

- xiaomi_vac/__init__.py
Sorry for creating two PRs for this change. I just don't know how to do it in one...
This was already in https://github.com/Bonze255/smarthomeNG_plugins/blob/98c3243397be7773d8738fee2625df844553ad29/xiaomi_vac/__init__.py#L323
I fear, some changes to this are missing
> xiaomi_vac plugin - Enable Segment Clean

- rcswitch/__init__.py
- rcswitch/plugin.yaml
- align plugin version numbers of __init__.py and plugin.yaml
- change version number to: 1.2.0.5
> [Bugfix: plugins/rcswitch]: align version number of plugin.yaml and __init__.py

- yamahayxc/plugin.yaml
- updated struct definition with relativ item references, so no further item config is necessary
- changed state to ready
> Plugin yamahayxc: updated struct definition, changed state to ready

- yamahayxc/plugin.yaml
too many dots in relative item reference...
> Plugin yamahayxc: fixed typo in struct definition

- influxdb/__init__.py
- influxdb/plugin.yaml
use self._get_parameter
option to use http or udp
updated metadata
> Plugin influxdb: update metadata and get_parameter, add udp/http feature

- gpio/README.md
- gpio/__init__.py
- gpio/plugin.yaml
- added global and per-item configuration to set pullup/pulldown mode
default (unconfigured) behaviour is unchanged compared to before
- added per-item configuration to invert in/out levels
- fixed startup code to prevent unwanted GPIO level changes
- code cleanup, removed unnecessary parts
- code tested, metadata updated and checked
> Plugin GPIO - reworked

- stateengine/README.md
- stateengine/StateEngineAction.py
- stateengine/StateEngineActions.py
- stateengine/StateEngineEval.py
- stateengine/StateEngineItem.py
- stateengine/StateEngineState.py
- stateengine/StateEngineTools.py
- stateengine/StateEngineValue.py
- stateengine/__init__.py
- stateengine/plugin.yaml
- stateengine/user_doc/06_aktionen.rst
lots of updates and improvements, see commits.
Needs to be tested though!
> Stateengine Plugin: Version 1.7.0

- stateengine/README.md
- stateengine/StateEngineAction.py
- stateengine/StateEngineCondition.py
- stateengine/StateEngineFunctions.py
- stateengine/StateEngineState.py
- stateengine/StateEngineTools.py
- stateengine/StateEngineValue.py
- stateengine/StateEngineWebif.py
- stateengine/__init__.py
- stateengine/locale.yaml
- stateengine/plugin.yaml
- stateengine/user_doc/05_bedingungen.rst
- stateengine/user_doc/06_aktionen.rst
- stateengine/webif/templates/visu.html
add regex, changedby and updatedby. some improvements
> Stateengine Plugin: version 1.7.2

- enocean/README.md
- enocean/__init__.py
- enocean/eep_parser.py
- enocean/plugin.yaml
- Rename of profile F6_02_03_01 -> F6_0G_03
- add POSITION
- Add new profile A5_0G_03
- update due to changes above
> [plugins/enocean]: Rework of Eltako Shutter Actor FSB71

- enocean/README.md
- enocean/eep_parser.py
- in README.md
- in eep_parser.py
> [smarhomeNG/plugins - enocean]: Correction of Typos

- nuki/README.md
- nuki/__init__.py
- nuki/locale.yaml
- nuki/plugin.yaml
- nuki/webif/templates/index.html
Nuki 2.0 supports door sensor states. The list of triggers and the update_lock_state function are extended to include those additional informations.
> add door sensor states

- bsblan/README.md
- bsblan/__init__.py
- bsblan/plugin.yaml
> New Plugin BSB-LAN-Adapter

- stateengine/plugin.yaml
- stateengine/user_doc/10_funktionen_variablen.rst
improve suspend_end/start eval
> Stateengine plugin: plugin.yaml fix and docu update

- mailrcv/__init__.py
plugins.mailrcv.IMAP Method plugins.mailrcv.IMAP exception: command: SELECT => IMAP4rev1 Server logging out
Hope it gets catched
> mailrcv: error handling if server is logging out while trying to select messages

- knx/__init__.py
> knx plugin: add debug message when sending knx telegram to bus

- alexarc4shng/__init__.py
Several problems/bugs found by pylint.
Added log warning with error text.
> plugin alexarc4shng: Several pylint fixes

- avdevice/webif/templates/index.html
webinterface add zone4, catch error when no dependson_item is given, prepare datatables view
> avdevice plugin: webIF improvements

- prowl/__init__.py
https://knx-user-forum.de/forum/supportforen/smarthome-py/1492644-support-thread-zum-prowl-plugin#post1597175
> Plugin prowl: fixed typo

- hue2/__init__.py
- hue2/plugin.yaml
- hue2/sv_widgets/widget_hue2.html
Add support for the "alert" and "effect" states.
> hue2: Adding states "alert" and "effect"

- hue/__init__.py
Current version does not correctly update .bri for group items, as code is looking in LampItems. Seems to be a copy&past problem.
New Version fixes this issue.
> hue plugin: Small BugFix in UpdateGoupItems

- uzsu/__init__.py
- uzsu/webif/__init__.py
- uzsu/webif/templates/index.html
showing the whole dictionary when a rule contains a "<" now
> uzsu plugin: outsource webif and fix webinterface problem 

- telegram/README.rst
- telegram/__init__.py
- telegram/plugin.yaml
- telegram/requirements.txt
- telegram/webif/__init__.py
- telegram/webif/templates/index.html
- Add possibility to send telegram message zu just 1 chat-id
- Add chat-if to "telegram_text" to allow response depending on chat-id
- Updated User Docu
- Updated WebIF
- Code Cleanup
> telegram Plugin:

- bose_soundtouch/README.md
- bose_soundtouch/__init__.py
- bose_soundtouch/plugin.yaml
> V1.0.1: Improved error handling

- uzsu/__init__.py
- uzsu/plugin.yaml
new PR based on latest develop-code. Moved setting the plugin version to run-method
> UZSU extensions for series - second try

- uzsu/__init__.py
- uzsu/plugin.yaml
update of item dict is now adjustable in plugin settings; some white space trimming
> uzsu plugin: sun calculation cron parameter

- stateengine/webif/static/img/visualisations/.gitignore
to make sure folder is created and files in folder are ignored.
> stateengine plugin: add gitignore to webif/visualizations folder 

- openweathermap/__init__.py
- openweathermap/plugin.yaml
- add struct for airpollution
- bumped to 1.8.4
> OWM Plugin:

- modbus_tcp/__init__.py
- modbus_tcp/example.yaml
- modbus_tcp/plugin.yaml
- modbus_tcp/user_doc.rst
- modbus_tcp/webif/__init__.py
- modbus_tcp/webif/templates/index.html
V1.0.5 kleine Fehler behoben
V1.0.4 ObjectType hinzugefügt (HoldingRegister, InputRegister, DiscreteInput, Coil)
Multiinstanz hinzugefügt
Verbindung schliessen nach Abruf aller Register
> modbus_tcp: version 1.0.5

- gpio/__init__.py
- gpio/plugin.yaml
- gpio/webif/__init__.py
- gpio/webif/templates/index.html
web interface (datatables, realtime values), convert debug messages to f-strings
> gpio plugin: update to 1.5.2 webif, f-string

- avdevice/plugin.yaml
- unifi/plugin.yaml
- uzsu/__init__.py
- uzsu/plugin.yaml
- uzsu/webif/__init__.py
- uzsu/webif/templates/index.html
> Plugin updates: avdevice, uzsu, unifi

- tasmota/__init__.py
- tasmota/plugin.yaml
- Bumped to version 1.2.1
- fixed bug in update_items
- Robustness improvement
> Tasmota Plugin: Bugfix and Robustness Improvement

- uzsu/__init__.py
- uzsu/plugin.yaml
- uzsu/webif/__init__.py
- uzsu/webif/templates/index.html
> uzsu plugin: update web interface to show highlight effect

- leveljet/__init__.py
- leveljet/plugin.yaml
- waterkotte/__init__.py
- waterkotte/plugin.yaml
This plugin adds support for Waterkotte Ecotouch heat pumps connected through LAN.
I have been using it since 2014, also see:
https://knx-user-forum.de/forum/supportforen/smarthome-py/39176-waterkotte-ecotouch-plugin
I've finally found the time to clean up the code (per pep8), fork/commit and create the pull request.
Also added a plugin for LevelJet fill level sensors connected through serial port. The plugin is from author knatter (KNX-User-Forum) and I have updated it to work with current SHNG and got his approval to add it to the pull request on his behalf.
> waterkotte: initial commit of Waterkotte plugin from private repo

- zigbee2mqtt/__init__.py
- zigbee2mqtt/plugin.yaml
- bumped to version 1.1.1
- added further parsing for last-seen
> Zigbee2Mqtt-Plugin

- stateengine/plugin.yaml
(issue when defined after suspend state)
last try with(out) tests ;)
> stateengine plugin: fix release state 

- husky2/__init__.py
- husky2/items.yaml
- husky2/plugin.yaml
- husky2/requirements.txt
- husky2/user_doc.rst
Made the changes discussed in the support forum
> husky2: updates and fixes

- xiaomi_vac/__init__.py
- xiaomi_vac/plugin.yaml
(after new firmware flash or reset). Dump to version 1.2.1
> xiamoi_vac plugin: fix issue when no cleaning details are found 

- stateengine/StateEngineAction.py
- stateengine/StateEngineActions.py
- stateengine/StateEngineCondition.py
- stateengine/StateEngineConditionSet.py
- stateengine/StateEngineEval.py
- stateengine/StateEngineItem.py
- stateengine/StateEngineState.py
- stateengine/StateEngineStruct.py
- stateengine/StateEngineTools.py
- stateengine/StateEngineValue.py
- stateengine/StateEngineWebif.py
- stateengine/plugin.yaml
- stateengine/user_doc/05_bedingungen.rst
- stateengine/user_doc/06_aktionen.rst
- stateengine/user_doc/10_funktionen_variablen.rst
- releasedby_handling
- new option to check for previous state and conditionsets
- minor issue fixing
> Stateengine Plugin: Some fixes and improvements

- openweathermap/sv_widgets/widgets_openweathermap.html
- rtr/sv_widgets/widget_rtr.html
- rtr2/sv_widgets/widget_rtr2.html
- simulation/sv_widgets/simulation.html
- stateengine/sv_widgets/stateengine.html
Twig / php otherwise throws warnings
> plugin SV widgets: set proper defaults in stateengine widget / update widget imports

- database/webif/templates/base_database.html
- database/webif/templates/index.html
- database/webif/templates/item_details.html
slightly improve code, webif layout and adjust update interval based on number of entries
> database plugin: webif updates

- hue2/__init__.py
fixes errors when using dict function (especially if dict is uninitialized)
> hue2: fix multiple functions at once

- smlx/__init__.py
- smlx/plugin.yaml
- changed way to make sure, that just one thread for read and parse is active (THX to bmxp, ohinckel)
- Code cleanup
- Adapt code to by compatible with Python 3.7
- Bumped to version 1.1.7
> SMLX Plugin: Changes / Improvement

- tasmota/__init__.py
- tasmota/plugin.yaml
- tasmota/user_doc.rst
- tasmota/webif/__init__.py
- tasmota/webif/templates/index.html
- Bumped to Version 1.3
- Implement Cluster und Group Commands for Zigbee
- Improved parsing of discovery message to detect and identify existing devices
- Improved start of subscriptions to notice all discovery messages
- Easy Zigbee data handling (more flat dict structure)
- Define allowed attribute values for tasmota_zb_attr
- added support for SHT3x sensor connected to Tasmota device
- Updated WebIF to latest http-module
- Code Cleanup and beautifying for better readability
> Tasmota-Plugin Update

- avdevice/webif/templates/index.html
to work with newest datatables changes
> avdevice plugin: fix web interface 

- knx/__init__.py
- knx/plugin.yaml
- knx/user_doc.rst
- knx/webif/__init__.py
- knx/webif/templates/index.html
first preparation for automatic data update in webif
> knx plugin: adjust webif_pagelength handling

- avm/__init__.py
- avm/tr064/config.py
- avm/webif/__init__.py
- avm/webif/templates/index.html
See commits for detailed description
> AVM Plugin: Bugfix

- avm/__init__.py
- avm/plugin.yaml
- avm/requirements.txt
- avm/tr064/config.py
- avm/webif/templates/index.html
- update requirements.txt to have lxml in 4.9.2
- update tr064/config.py to have receive correct error numbers from device
- introduce new plugin-parameter 'tr064_item_blacklist' and update code accordingly
- update item even if poll result is None
- Update WebIF
- code cleanup
> AVM Plugin

- db_addon/__init__.py
- db_addon/item_attributes_master.py
- db_addon/plugin.yaml
- db_addon/user_doc.rst
- db_addon/webif/__init__.py
- db_addon/webif/templates/index.html
- allow db_addon item to be written in database itself
- introduce new parameter to configure database-item explicitly
- add methods to calculate tagesmitteltemperatur
- change Wärmesumme to use whole year
- introduce Wachstumsgradtage
- bugfixing
- code clean up
- update user_doc
- update WebIF
> DB_ADDON Plugin

- husky2/__init__.py
- husky2/plugin.yaml
- husky2/requirements.txt
- husky2/webif/templates/index.html
- Catch exception on plugin shutdown
- Moved to actual aioautomower version
- Cleanup
- Imroved/fixed webif tables
> husky2: update

- zigbee2mqtt/__init__.py
- zigbee2mqtt/plugin.yaml
- update plugin.yaml by adding documentation path and support link
> Zigbee2MQTT Plugin:

- db_addon/__init__.py
- db_addon/item_attributes.py
- db_addon/item_attributes_master.py
- db_addon/plugin.yaml
- db_addon/user_doc.rst
- db_addon/webif/templates/index.html
- Remove use of _plg_item_dict in WebIF
- automate generation of file item_attributes.py and update of plugin.yaml per script in item_attributes_master.py
- update docu
- bump to 1.1.2
> DB-ADDON Plugin:

- avm/__init__.py
- avm/plugin.yaml
- bump to version 2.0.7
- improve login; if sid has expired a new one will be generated automatically
- improve get requests
- deactivate scheduler for check_sid; Plugin will re-login of sid has expired
- improve check if request response is string prior to parse element from string
- update handle_updated_item in FritzHome to handle all avm_data_types
- implement new method to update all items connected to ain
- restructure, simplify, harmonize coding in FritzHome
- bugfix in debug_log in cyclic_item_update
> AVM Plugin: Improve Fritz_Home

- knx/__init__.py
All polls are put in a waiting list and polled on run only.
> knx plugin: fix issue with polling knx items on startup. 

- modbus_tcp/__init__.py
- Fixed bug in __write_Registers() on sending float32 because of missing else in if
- Changed scheduler_add call to meet the plugin scheduler criteria
> modbus_tcp: Fixed bug 

- stateengine/StateEngineLogger.py
Custom logger stateengine.<item>.rules
> stateengine plugin: (re)introduce separate loggers for each item

- tasmota/webif/templates/index.html
- revert direct use of _plg_item_dict in WebIF
> Tasmota Plugin: revert direct use of _plg_item_dict in WebIF

- vacations/__init__.py
- vacations/plugin.yaml
update after start
update cycle configurable
accept country "Germany"
> update vacations plugin

- tasmota/__init__.py
- tasmota/plugin.yaml
> Tasmota: Improve Exception handling and handling of power messages

- husky2/__init__.py
- husky2/sv_widgets/husky2.html
- husky2/sv_widgets/husky2.js
- Added a poll function
- Improved google maps script loading in sv widget
> Husky2: minor updates

- rcs1000n/__init__.py
- rcs1000n/cRcSocketSwitch/cRcSocketSwitch.py
- restructure send with respect of clean code
- improve try except clause
> [rcs1000n]: restructure send method and improve try except clause

- stateengine/StateEngineEval.py
- stateengine/StateEngineItem.py
- stateengine/StateEngineState.py
- stateengine/StateEngineTools.py
- stateengine/StateEngineValue.py
- stateengine/plugin.yaml
- stateengine/user_doc/03_regelwerk.rst
- stateengine/user_doc/04_zustand.rst
- stateengine/user_doc/05_bedingungen.rst
- stateengine/user_doc/08_beispiel.rst
- stateengine/user_doc/09_vorlagen.rst
- stateengine/user_doc/13_sonstiges.rst
- stateengine/webif/templates/visu.html
> Stateengine Plugin: new se_stateorder functionality, list items, more updates

- byd_bat/__init__.py
- byd_bat/locale.yaml
- byd_bat/plugin.yaml
- byd_bat/user_doc.rst
- byd_bat/webif/__init__.py
- byd_bat/webif/templates/index.html
bug fixing and extension for more modules
> byd_bat plugin: V0.0.7 several modifications

- stateengine/StateEngineAction.py
to now set the value to current+0.1
> stateengine plugin: change force action 

- ksemmodbus/README.md
- ksemmodbus/__init__.py
- ksemmodbus/_pv_1_6_2/README.md
- ksemmodbus/_pv_1_6_2/__init__.py
- ksemmodbus/_pv_1_6_2/files/kostal_item_template.yaml
- ksemmodbus/_pv_1_6_2/ksem.py
- ksemmodbus/_pv_1_6_2/plugin.yaml
- ksemmodbus/_pv_1_6_2/requirements.txt
- ksemmodbus/ksem.py
- ksemmodbus/plugin.yaml
- ksemmodbus/requirements.txt
- Support für pymodbus 2 entfernt
- nicht getestet
- Vorversion gesichert
> Ksemmodbus

- db_addon/__init__.py
- db_addon/plugin.yaml
- db_addon/user_doc.rst
change to 1.2.8
bugfix in wachstumsgradtage
bugfix in database query with function "next"
bugfix in kaeltesumme
> DB_ADDON Plugin Bugfix

- homematic/__init__.py
- homematic/plugin.yaml
I did not update the Version yet, not sure if i should.
> Customizable Callback and ProxyPorts for homematic

- avm/__init__.py
Unfortunately, after the last update, some AVM functions no longer work as before. As this appears to be a typing error, please accept the bugfix
> AVM: Bugfix get_calllist and get_contact_name_by_phone_number

- alexa4p3/plugin.yaml
fixed duplicate entry for alexa_item_range
> alexa4p3: update plugin.yaml

- sonos/__init__.py
- sonos/plugin.yaml
- bump to 1.8.10
- bugfix for dpt3 handling
> SONOS: Bugfix

- avm/__init__.py
- avm/plugin.yaml
- bump to 2.2.3
- bugfix initial item update
- update public functions of plugin with check if device is available
> AVM: Bugfix
